swagger: '2.0'
info:
  title: Sample API
  description: API description in Markdown.
  version: "1.0.0"
servers:
  - url: http://localhost:3000/api/v1
paths:
  /api/meditation:
    get:
      tags:
        - Songs Collection
      summary: Get all songs by Genre
      responses:
        200:
          description: An array of songs
          schema:
            type: array
            items:
              $ref: '#/definitions/Song'
          examples:
            application/json:
              "@namespaces":
                meditationService:
                  name: "/meditation_link_relation"
              songs:
                - "@controls":
                    item:
                      href: "/song/7"
                      method: "GET"
                      title: "Get Song by song_id"
                  song_artist: "lilMozart"
                  song_duration: 3.52
                  song_genre: "Classical"
                  song_id: 7
                  song_name: "Classic4"
                - "@controls":
                    item:
                      href: "/song/9"
                      method: "GET"
                      title: "Get Song by song_id"
                  song_artist: "lilMozart"
                  song_duration: 3.52
                  song_genre: "Classical"
                  song_id: 9
                  song_name: "Classic5"
                - "@controls":
                    item:
                      href: "/song/10"
                      method: "GET"
                      title: "Get Song by song_id"
                  song_artist: "lilMozart"
                  song_duration: 3.52
                  song_genre: "Classical"
                  song_id: 10
                  song_name: "Classic7"
        400:
          description: Empty request body
        401:
          description: API key is missing
        415:
          description: Unsupported Media Type, This service accept JSON input.
        404:
          description: Failed to retrieve songs
        500:
          description: Internal Server Error
      security:
        - BearerAuth: []
        - X-API-Key: []
  /api/song/{song_id}:
    get:
      tags:
        - Song
      summary: Get a single song by ID
      parameters:
        - in: path
          name: song_id
          required: true
          schema:
            type: integer
          description: Unique identifier of the song
      responses:
        200:
          description: A song object
          schema:
            $ref: '#/definitions/Song'
          examples:
            application/json:
              "@namespaces":
                custWorkoutPlaylistGen:
                  name: "/song_link_relation"
              "@controls":
                collection:
                  method: GET
                  title: List All Songs
                  href: /api/song
                edit:
                  method: PUT
                  title: Edit This Song
                  encoding: json
                  schema:
                    type: object
                    required:
                      - song_name
                      - song_artist
                      - song_genre
                      - song_duration
                    properties:
                      song_name:
                        description: Name of the song
                        type: string
                      song_artist:
                        description: Artist of the song
                        type: string
                      song_genre:
                        description: Genre of the song
                        type: string
                      song_duration:
                        description: Duration of the song
                        type: number
                  href: /api/song/4
                delete:
                  method: DELETE
                  title: Delete This Song
                  href: /api/song/4
                profile:
                  href: /profile
              song_id: 4
              song_name: Pop5
              song_artist: lilMozart
              song_genre: Pop
              song_duration: 4.52
        404:
          description: Song not found
      security:
        - BearerAuth: []
        - X-API-Key: []
securityDefinitions:
  BearerAuth:
    type: apiKey
    in: header
    name: Authorization
    description: Enter your bearer token in the format **Bearer <token>**
  X-API-Key:
    type: apiKey
    in: header
    name: X-API-Key
    description: "Enter your API key in the X-API-Key header"
definitions:
  Song:
    type: object
    required:
      - song_name
      - song_artist
      - song_genre
      - song_duration
    properties:
      song_name:
        type: string
        description: Name of the song
        example: "Summer Nights"
      song_artist:
        type: string
        description: Artist of the song
        example: "John Doe"
      song_genre:
        type: string
        description: Genre of the song
        example: "Pop"
      song_duration:
        type: float
        description: Duration of the song in minutes
        example: 3.5